-- ============================================================================
-- STXRYAI MASTER DATABASE SETUP - RUN ALL PARTS
-- ============================================================================
-- Version: 3.0.0 | Date: December 23, 2024
-- 
-- This file is a reference guide. To run the complete setup:
-- Execute each part file IN ORDER in your Supabase SQL Editor.
-- 
-- ============================================================================
-- EXECUTION ORDER:
-- ============================================================================
-- 
-- 1. STXRYAI_MASTER_SETUP.sql       (Part 1: Extensions, Enums, Core tables)
-- 2. STXRYAI_MASTER_SETUP_PART2.sql (Part 2: Social, Messaging, Monetization)
-- 3. STXRYAI_MASTER_SETUP_PART3.sql (Part 3: AI/Narrative Engine, Global Story)
-- 4. STXRYAI_MASTER_SETUP_PART4.sql (Part 4: Creator Tools, Adaptive AI)
-- 5. STXRYAI_MASTER_SETUP_PART5.sql (Part 5: TTS, Events, Moderation, GDPR)
-- 6. STXRYAI_RLS_POLICIES.sql       (Part 6: All RLS policies)
-- 
-- ============================================================================
-- WHAT'S INCLUDED:
-- ============================================================================
-- 
-- CORE TABLES (~30):
--   • user_profiles, users, user_preferences, user_levels, user_stats
--   • stories, story_chapters, chapters, story_choices, choices
--   • reading_progress, user_reading_progress, user_progress
--   • bookmarks, story_bookmarks, comments
-- 
-- GAMIFICATION (~20):
--   • achievements, user_achievements, user_badges
--   • reading_streaks, user_reading_streaks
--   • daily_reading_goals, reading_calendar
--   • weekly_challenges, monthly_challenges, daily_challenges
--   • milestones, community_competitions, leaderboard
-- 
-- SOCIAL (~15):
--   • user_friendships, friendships, user_follows
--   • story_reviews, reviews, story_likes
--   • user_reading_lists, reading_list_items
--   • notifications, referrals, referral_rewards
-- 
-- MESSAGING (~8):
--   • conversations, messages, conversation_participants
--   • typing_indicators, message_reactions
--   • announcements, dismissed_announcements
-- 
-- COMMUNITY HUB (~10):
--   • reading_clubs, club_members
--   • discussion_forums, discussion_replies
--   • community_events, event_participants
--   • mentorship_programs, user_reputation
-- 
-- MONETIZATION (~15):
--   • user_wallets, coin_transactions, subscriptions
--   • content_unlocks, offline_downloads
--   • premium_story_pricing, story_purchases
--   • creator_payouts, creator_earnings, creator_tips
--   • story_collections, character_packs
-- 
-- AI & NARRATIVE ENGINE (~25):
--   • ai_generations, reader_story_sessions
--   • story_series, series_books
--   • persistent_characters, character_events, character_book_states
--   • world_elements, narrative_arcs
--   • canon_rules, canon_violations, continuity_notes
--   • global_stories, global_story_chapters, global_story_actions
-- 
-- CREATOR TOOLS (~15):
--   • story_drafts, chapter_drafts, draft_comments
--   • story_collaborators, collaboration_sessions
--   • writing_templates, marketing_campaigns
--   • creator_analytics_snapshots, story_performance_tracking
-- 
-- ADAPTIVE AI (~20):
--   • user_reading_preferences, story_adaptation_log
--   • choice_predictions, personalized_narrative_paths
--   • ai_writing_suggestions, plot_doctor_analyses
--   • ai_idea_generations, writing_assistant_sessions
--   • user_engagement_metrics, story_npcs, npc_memory
-- 
-- TTS & LIVE EVENTS (~12):
--   • tts_voices, character_voices, audio_generations
--   • audio_playback_sessions, user_tts_preferences
--   • live_events, event_registrations, event_messages
--   • event_questions, event_polls, poll_responses
-- 
-- MODERATION & GDPR (~10):
--   • ai_moderation_logs, moderation_queue, content_flags
--   • user_consents, data_export_requests, data_deletion_requests
--   • privacy_settings, cookie_preferences
-- 
-- ============================================================================
-- TOTAL: ~180+ TABLES
-- ============================================================================
-- 
-- ALSO INCLUDES:
--   • All required ENUMS (25+)
--   • All INDEXES for performance (100+)
--   • All RLS POLICIES for security
--   • All FUNCTIONS for business logic
--   • All TRIGGERS for automation
--   • SAMPLE DATA (achievements, stories, donation tiers)
-- 
-- ============================================================================
-- NOTES:
-- ============================================================================
-- 
-- 1. Run in a FRESH Supabase project
-- 2. Execute parts in order (1-6)
-- 3. Each part depends on previous parts
-- 4. If a table already exists, it will be skipped (IF NOT EXISTS)
-- 5. After setup, verify with: SELECT COUNT(*) FROM pg_tables WHERE schemaname = 'public'
-- 
-- ============================================================================

SELECT '📋 Read this file for setup instructions. Execute parts 1-6 in order.' AS instructions;


